services:
  problem_solving_agency:
    container_name: problem_solving_agency
    build:
      context: ./problem_solving_agency
      dockerfile: Dockerfile
    env_file:
      - ./stack.env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - app:/app
    ports:
      - 10007:7860

volumes:
  app:
